[phases.setup]
aptPkgs = ['libgl1', 'libglib2.0-0', 'libsm6', 'libxext6', 'libxrender1', 'libgomp1', 'libgthread-2.0-0']

[phases.install]
cmds = ['pip install --no-cache-dir -r requirements.txt']

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'