[build]
nixpacksPlan = "nixpacks.toml"

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300

[variables]
QT_QPA_PLATFORM = "offscreen"
OPENCV_IO_ENABLE_OPENEXR = "0"